version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    network_mode: host
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
      - ./auth:/etc/nginx/auth
      - ./cache:/var/nginx/cache
      - /var/www:/var/www
