version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    network_mode: host
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx:/etc/nginx/conf.d
      - ./auth:/etc/nginx/auth
      - ./html:/etc/nginx/html
      - ./cache:/var/nginx/cache
      - ./logs:/var/log/nginx
      - ./well-known:/well-known
      - /var/www:/var/www
